made this compatible with windows
palantir/python-jsonrpc-server pull request #22
Opened 2019-08-15 09:12 UTC by absolute-cretin

I was messing around with the pyls source code and I kept getting an error. Stepped through it with a debugger and realized that this line of code doesn't account for windows line endings. I fixed it so now it does work

2019-08-15 09:12 UTC, palantirtech commented
Thanks for your interest in [palantir/python-jsonrpc-server](https://github.com/palantir/python-jsonrpc-server), @absolute-cretin! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

2019-08-21 10:06 UTC, absolute-cretin commented
Hi, I have signed the agreement :)

2019-08-21 11:59 UTC, gatesn requested changes

2019-08-21 11:59 UTC, gatesn commented on pyls_jsonrpc/streams.py
> +            # to check for windows line endings
I don't quite understand why this is necessary here? Doesn't the line `while line and line.strip()` strip all whitespace, including windows line endings? 

What is your rfile where you're seeing this break?

2020-09-07 21:23 UTC, delta003 commented
Stale

2020-09-07 21:23 UTC, closed without merging